# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'PhotoNote' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoNote
 pod 'Firebase'
 pod 'Firebase/Core'
 pod 'Firebase/Database'
 pod 'Firebase/Auth'
 pod 'FirebaseFirestoreSwift'

end
